# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - develop
  - release/*

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Test
    jobs:
    - job: master
      pool: 
        vmImage: 'windows-2019'
      steps:
      - task: NuGetToolInstaller@1

    - job: develop
      pool: 
        vmImage: 'windows-2019'
      steps:
      - task: NuGetToolInstaller@1
    
    - job: release
      pool: 
        vmImage: 'windows-2019'
      steps:
      - task: NuGetToolInstaller@1